### ISSUE TITLE
[API] CLI updating objects should trigger a JSON schema validation

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-Core#10]
In a `obj:color=value` command, the CLI should check if "value" is a valid hexadecimal color
```
cedrok@OGrEE3D:/Physical$> DEMO/BASIC/A/R1/B09:color=AA12g4
OK. Attempting to update...
Success
```

An other error: 
For a corridor, "temperature" attribute can only be "cold" or "warm"
```
cedrok@OGrEE3D:/Physical$> DEMO/BASIC/A/R1/CO2:temperature=patate
OK. Attempting to update...
Success
```

**Comment by helderbetiol** [comment]
A correct validation using json schemas for PATCH requests was added alongside a color attribute for rack, device and group schemas.
