### ISSUE TITLE
[API][CLI] : add automatic "layers" based on category/types/tags

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-Core#102]
In order to be able to "hide/show" some children of any object.

a subdirectory "layers" in every object with at least one child should be created

```
cd /P/SITE/BUILDING/ROOM
ls 
B05
..
C15
Porthos
|
+ layers : 
     @doors  : ls "category=generic&type=door" from "." = SITE/BUILDING/ROOM     || automatic layers
     @servers  : ls "category=devices&type=server"                               || automatic layers
     @switches :  ls "category=devices&type=switch"                              || automatic layers
     xeon     : ls "category=devices&type=cpu&model="xeon"  :                    || user defined / custom
```

- hide/ show

```
admin@tenant:/Physical>  draw SITE 3  // (until rack/doors/corridors)
admin@tenant:/Physical>  hide  @doors   // hide all doors displayed in 3D scene
admin@tenant:/Physical>  hide  SITE@doors  // hide all doors displayed in SITE site
admin@tenant:/Physical>  hide  SITE.BUILDING.ROOM.@doors // hide all doors of ROOM
admin@tenant:/Physical>  show  @doors
```

**Comment by FrancoLiberali** [comment]
Layers are added automatically when you ls an object. They are shown at the end of the list and start with # (for example #racks for a room). It is possible to do ls and get on a layer, which will list and display all the information of the objects that belong to the layer, respectively. Cd and tree on layers are not allowed.

As for the hide and show layer part, I honestly forgot about it. So, they were not implemented but they are not commands that do not exist in the cli (another issue should be created about it?). Anyway, undraw does exist but the operation is not direct, you must first make a select of the layer and then undraw. I don't know what is the behavior of undrawing directly on a layer, I will verify it and correct it if necessary.

**Comment by FrancoLiberali** [comment]
A new pull request has been created to add this feature: https://github.com/ditrit/OGrEE-Core/pull/302
