### ISSUE TITLE
Inconsistent "t" vs "tile"

### ISSUE THREAD

**Issue by GeremWD** [ditrit/OGrEE-Core#126]
Currently, we have 't' for the 'floorUnit' field of a room and 'tile' for the 'posXYUnit' field of a rack. We should only accept 'tile' for both.

**Comment by helderbetiol** [comment]
For the API, in both room_schema and rack_schema, the only accepted unit is already t:
- rack_schema
```
"posXYUnit": {
          "type": "string",
          "enum": ["m", "t", "f"]
        },
```
- room_schema
```
"floorUnit": {
          "type": "string",
          "enum": ["m", "t", "f"]
        },
```
