### ISSUE TITLE
CLI should check template type before using

### ISSUE THREAD

**Issue by GeremWD** [ditrit/OGrEE-Core#203]
The CLI does not check the type of a template before using it to create an object.
Example :
```
+rk:test@[9,1]@m@right@ibm-ns1200
```
where ibm-ns1200 is a device template.
All the required rack attributes are present in the device template, so the command runs without error and the object is created.

**Comment by Barbozafab** [comment]
This bug was fixed on PR #321 , more specifically on commit 912ba30535ede6b5a444755dfc3a83911d601d99 by @FrancoLiberali in November, 2023.
