### ISSUE TITLE
dbForTenants : Sites should be unique

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-Core#22]
This shouldn't be possible:
```
cedrok@DEMO:/Physical> +si:TEST
successfully created object
cedrok@DEMO:/Physical> +si:TEST
successfully created object
cedrok@DEMO:/Physical> +si:TEST
successfully created object
cedrok@DEMO:/Physical> ls
Stray
TEST
TEST
TEST
```

**Comment by helderbetiol** [comment]
This is configured directly in the database with a script in the moment of creation. The docker compose in ogree server is not up to date with dbft, I'll update it to avoid this type of issue.
