### ISSUE TITLE
Logical operators in layers filters

### ISSUE THREAD

**Issue by FrancoLiberali** [ditrit/OGrEE-Core#278]
Currently, the layer filters have an implicit & and do not allow the use of other logical operators.

**Comment by Barbozafab** [comment]
I've created a new option for `ls` and `get` to perform searches with complex filters, composing complex boolean expressions with the operators `=`, `!=`, `<`, `<=`, `>`, `>=`, `&` and `|`. A complex filter can be specified by utilising the option `-f` before the filter.

```
ls . -f (category = corridor) | (name = R1 & height > 10)
get * -f category != rack & category != corridor
```

The searches with complex filters is handled by a new function, `HandleComplexFilters`, which in turn is served by a new API endpoint, `/api/objects/search`. This endpoint is called by a `POST` method, and the complex MongoDB search pattern is passed as the body of the HTTP call. 

**Note**:
The `ls` command used to have an option `-f attributes` for listing the results with the attributes present in format. This option was renamed to `-a attributes`.
