### ISSUE TITLE
Better validation error messages

### ISSUE THREAD

**Issue by FrancoLiberali** [ditrit/OGrEE-Core#291]
When a validation error occurs in any attribute of an object, the cli displays a message like the following:

Error: [Response From API] JSON body doesn't validate with the expected JSON schema
/slug does not match pattern '^[a-z0-9-_]+$'

These errors should be more readable

**Comment by Barbozafab** [comment]
I've added logic to substitute the regex pattern in validation error messages for a friendlier description
