### ISSUE TITLE
labelBackground not working

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-Core#357]
The *labelBackground* command should send an **interact** command to the 3D client instead of a **modify** one.
For example:
`BASIC/A/R1/A01:labelBackground=ced000` si currently creating an attribute *labelBackground* instead of triggering a *modify* command (like *labelFont* for exampe)
```json
{
  "data":
  {
    "attributes":
    {
      "color":"AA00BB",
      "height":"42",
      "heightUnit":"U",
      "labelBackground":"ced000",
      "posXYUnit":"t",
      "posXYZ":"{\"x\":1 ,\"y\":2 ,\"z\":0 }",
      "rotation":"{\"x\":0, \"y\":0, \"z\":180}",
      "size":"{\"x\":60 ,\"y\":120 }",
      "sizeUnit":"cm",
      "template":""
    },
    "category":"rack",
    "createdDate":"2023-08-25T11:14:54.19Z",
    "description":[],
    "domain":"test",
    "id":"BASIC.A.R1.A01",
    "lastUpdated":"2024-01-22T13:59:05.107Z",
    "name":"A01",
    "parentId":"BASIC.A.R1",
    "tags":[]
  },
  "type":"modify"
}
```

(Wiki link: https://github.com/ditrit/OGrEE-Core/wiki/CLI-language#modify-labels-background-color)

**Comment by Barbozafab** [comment]
I've added functionality to make labelBackground send an **interact** command to the 3D client instead of a **modify** one
