### ISSUE TITLE
Change attribute's vector format to array

### ISSUE THREAD

**Issue by helderbetiol** [ditrit/OGrEE-Core#363]
Object attributes with type vector3 or vector2 expect a string formatted as a dictionary with coordinates (x,y,z) as keys and floats as values. The proposed change is to expect a string formatted as an array of floats where each element will respectively correspond to x, y and z. Spaces between numbers and commas are accepted and should be ignored. Examples:

- `"posXYZ" : "{"x":45 ,"y":50 ,"z":35}"` becomes `"posXYZ" : "[45, 50, 35]"`
- `"size" : "{"x":45 ,"y":50}"` becomes `"size" : "[45, 50]"`

This impacts CLI, API and 3D.

**Comment by Barbozafab** [comment]
- The `vector2` format was changed from `{"x":x, "y":y}` to `[x, y]`

- The `vector3` format was changed from `{"x":x, "y":y, "z":z}` to `[x, y, z]`

**Comment by helderbetiol** [comment]
Same thing applies for `reserved` and `technical` for rooms, now it's a map and it should become an array.

**Comment by Barbozafab** [comment]
Done!

- The reserved and technical format was changed from {"left":x, "right":y, "top":z, "bottom":w} to [z, w, y, x]
