### ISSUE TITLE
[CLI] attribute label could be a list of mixed attributes

### ISSUE THREAD

**Issue by Novanef** [ditrit/OGrEE-Core#37]
`FOOBAR.Site.CTN.R1.RF:label=#description,#weight,#attribute1,...#attributeN`

group | corridor | rack | device

**Comment by Barbozafab** [comment]
Created a simple parser for the labels that supports labels with multiple attributes, substituting all values correctly.

Note: to use commas in the label, it is necessary to surround if with quotes (e.g. `FOOBAR.Site.CTN.R1.RF:label="#description,#weight,#attribute1,...#attributeN"`).
