### ISSUE TITLE
 manage flipped PCI adapters in servers

### ISSUE THREAD

**Issue by Novanef** [ditrit/OGrEE-Core#39]
PCI adapters can be placed in 3 ways in server

- vertically
- horizontally front top
- horizontally back top

horizontal adapters could be with pci connector on right or left

on REAR of server , +X is right to left <-----+x--------

if adapter is smaller (width) than slot, it will be stacked on right of slot.
if adapter is "back top" => adapter should be stacked on left of slot

2 solutions : 
- add another "side" verb for device, "upsidedown" or "flipped"
- add option for slot in JSON model
- 
![image](https://user-images.githubusercontent.com/61938544/126874969-15f81b6d-792d-43bd-9cc9-50fdc2ac1461.png)
![image](https://user-images.githubusercontent.com/61938544/126874981-3f18189b-7b11-4ed1-a730-2fb81c156771.png)

Doc is here D:\Nextcloud.ditrit\Ogree\5_Misc\adapter_front_back_top.docx

**Comment by helderbetiol** [comment]
We currently have orientation for devices accepting one of the following: "front", "rear", "frontflipped", "rearflipped". @Novanef could you check if this is enough and we can close the issue?

**Comment by helderbetiol** [comment]
Add a new non-mandatory attribute to device create command on CLI. Add new attribute to device schema on the API that accepts only two values: "true" or "false". Attribute's name: invertOffset. Default value: "false". When "true", the 3D client will invert the default offset of the device. Currently, default offset is to the left. If inverted, it will be to the right.
