### ISSUE TITLE
Delete attribute of an object

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-Core#436]
We want to be able to remove an attribute from an object. This attribute should not requiered (check in json schema)
The command can `-name.attribute` ?
eg:
`-/P/BASIC/A/R1/A01:color`

**Comment by helderbetiol** [comment]
We already have such command! You can remove the attribute of an object with the `unset` command:
```
admin@TenantName:/Physical> man unset
USAGE:  unset [OPTIONS] [VAR/FUNC NAME]     
Deletes function or variable or attribute of an object   

There is an alternative usage for deleting an attribute of an object or an element in an attribute:   

unset [PATH/TO/OBJECT]:[ATTRIBUTE]
unset [PATH/TO/OBJECT]:[ATTRIBUTE][INDEX]

Note that the attribute must be in quotes!
OPTIONS

-v    Deletes variable
-f    Deletes function

EXAMPLE   

    unset -v myVariable
    unset -f myFunc
    unset path/to/room:attribute1
    unset path/to/object:description[3]
 ```
 I will update this man page (description no longer an array) and add it to the CLI Language doc page. Let me know if it works for you.

**Comment by helderbetiol** [comment]
Changed the syntaxe of unset attribute to the one proposed y this issue. The command unset is now only for vars and functions of the CLI environment.
