### ISSUE TITLE
Retrieve site colors from an endpoint

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-Core#438]
We need an API endpoint to retrieve colors attributes from the parent site of a room
Something like `/api/sitecolors/roomId` 
Which give colors attributes: 
```json
"reservedColor": "",
"technicalColor": "",
"usableColor": ""
```

**Comment by helderbetiol** [comment]
`/api/sitecolors/{id}`: added this new GET endpoint that accepts any objet ID and returns de colors of the parent site:
```
GET /api/sitecolors/Site.Bldg.MyRoom
{
    "data": {
        "reservedColor": "AEEEEE",
        "technicalColor": "D0FF78",
        "usableColor": "5BDCFF"
    },
    "message": "successfully got attribute from object's parent site"
}
```
If one of the 3 expected colors is not present in the parent site, that color is returned with an empty string as value. Example for a site with no colors:

```
{
    "data": {
        "reservedColor": "",
        "technicalColor": "",
        "usableColor": ""
    },
    "message": "successfully got attribute from object's parent site"
}
```
