### ISSUE TITLE
updated / easy to maintain endpoints list

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-Core#57]
find a way to have an uptodate list of all endpoints, sorted by HTTP method (GET/POST/PUT/PATCH) and by  category

should be on website at least in MarkDown / Wiki format
should be used to update swagger after

This exhaustive list will be used by frontend dev soon and cedric is waiting for it

**Comment by GeremWD** [comment]
We have the swagger so I think we can close that one
